version: "3"
services: 
  lb:
    image: nginxapp
    ports: 
      - "8080:8080"
  waddup1:
    image: nodeapp
    environment: 
      - PORT=8001
    ports: 
      - "8001:8001"
  waddup2:
    image: nodeapp
    environment: 
      - PORT=8002
    ports: 
      - "8002:8002"
  waddup3:
    image: nodeapp
    environment: 
      - PORT=8003
    ports: 
      - "8003:8003"
